export const marketDrugs = [
  {
    name: "Weed",
    basePrice: 100,
    quantity: 10,
    minPrice: 50,
    maxPrice: 150,
    selected: false,
  },
  {
    name: "Cocaine",
    basePrice: 200,
    quantity: 5,
    minPrice: 100,
    maxPrice: 250,
    selected: false,
  },
  {
    name: "Heroin",
    basePrice: 300,
    quantity: 3,
    minPrice: 150,
    maxPrice: 400,
    selected: false,
  },
  {
    name: "Meth",
    basePrice: 400,
    quantity: 2,
    minPrice: 200,
    maxPrice: 500,
    selected: false,
  },
  {
    name: "Ecstasy",
    basePrice: 180,
    quantity: 6,
    minPrice: 90,
    maxPrice: 270,
    selected: false,
  },
  {
    name: "LSD",
    basePrice: 250,
    quantity: 4,
    minPrice: 120,
    maxPrice: 350,
    selected: false,
  },
  {
    name: "Crack",
    basePrice: 220,
    quantity: 5,
    minPrice: 110,
    maxPrice: 330,
    selected: false,
  },
  {
    name: "Mushrooms",
    basePrice: 150,
    quantity: 7,
    minPrice: 75,
    maxPrice: 225,
    selected: false,
  },
  {
    name: "Adderall",
    basePrice: 130,
    quantity: 8,
    minPrice: 65,
    maxPrice: 195,
    selected: false,
  },
  {
    name: "Ritalin",
    basePrice: 120,
    quantity: 8,
    minPrice: 60,
    maxPrice: 180,
    selected: false,
  },
  {
    name: "Ketamine",
    basePrice: 270,
    quantity: 4,
    minPrice: 135,
    maxPrice: 405,
    selected: false,
  },
  {
    name: "GHB",
    basePrice: 160,
    quantity: 6,
    minPrice: 80,
    maxPrice: 240,
    selected: false,
  },
  {
    name: "Fentanyl",
    basePrice: 500,
    quantity: 1,
    minPrice: 250,
    maxPrice: 700,
    selected: false,
  },
  {
    name: "Oxycodone",
    basePrice: 350,
    quantity: 3,
    minPrice: 175,
    maxPrice: 525,
    selected: false,
  },
  {
    name: "MDMA",
    basePrice: 190,
    quantity: 6,
    minPrice: 95,
    maxPrice: 285,
    selected: false,
  },
  {
    name: "PCP",
    basePrice: 300,
    quantity: 3,
    minPrice: 150,
    maxPrice: 450,
    selected: false,
  },
  {
    name: "Quaaludes",
    basePrice: 210,
    quantity: 5,
    minPrice: 105,
    maxPrice: 315,
    selected: false,
  },
  {
    name: "Methadone",
    basePrice: 230,
    quantity: 4,
    minPrice: 115,
    maxPrice: 345,
    selected: false,
  },
];

export const playerRanks = [
  { name: "Newbie", minCash: 0, maxCash: 1000 },
  { name: "Dealer", minCash: 1001, maxCash: 5000 },
  { name: "Kingpin", minCash: 5001, maxCash: 10000 },
  { name: "Drug Lord", minCash: 10001, maxCash: 100000 },
];

export const randomEvents = [
  { name: "Police Raid", cashChange: -500, drugsChange: -5 },
  { name: "Drug Bust", cashChange: -1000, drugsChange: -10 },
  { name: "Mugging", cashChange: -100, drugsChange: -1 },
  { name: "Casino Win", cashChange: 500, drugsChange: 0 },
];

export const locations = [
  { name: "New York", drugPrices: [100, 200, 300, 400] },
  { name: "Los Angeles", drugPrices: [120, 220, 320, 420] },
  { name: "Miami", drugPrices: [110, 210, 310, 410] },
  { name: "Chicago", drugPrices: [130, 230, 330, 430] },
];
